import type { RuleSource } from './rules.js';

/** Relative path (from workspace root) of the chamba workspace file. */
export const WORKSPACE_DIR = '.chamba';
export const WORKSPACE_FILE = 'workspace.md';
export const WORKSPACE_RELATIVE_PATH = `${WORKSPACE_DIR}/${WORKSPACE_FILE}`;

/** An auth library/provider detected in one project, with the packages that signalled it. */
export interface ProjectAuth {
  provider: string;
  packages: string[];
}

/** A workspace-level auth finding: a provider, the packages, and where it's used. */
export interface AuthFinding {
  /** Provider/library, e.g. "Auth0", "Firebase Auth", "AWS Cognito". */
  provider: string;
  /** Dependency names that signalled it. */
  packages: string[];
  /** Project names where it was detected. */
  projects: string[];
}

/** Mobile target platform. */
export type MobilePlatform = 'ios' | 'android';

/**
 * A React Native / Expo app detected in one project — what the QA co-pilot needs
 * to run acceptance tests on a simulator/emulator. Detection only: chamba never
 * boots a device, it lists what the project targets and what tooling it ships.
 */
export interface MobileTarget {
  /** Expo flavor, when Expo is present: managed (no native dirs) or bare/prebuilt. */
  expo?: 'managed' | 'bare';
  /** `react-native` is a direct dependency. */
  reactNative: boolean;
  /** Target platforms detected (native dirs, or both by default for managed Expo). */
  platforms: MobilePlatform[];
  /** `eas.json` is present (EAS Build/Submit configured). */
  hasEas: boolean;
  /** `expo-dev-client` is a dependency (custom dev client, not plain Expo Go). */
  hasDevClient: boolean;
  /** Mobile E2E tooling detected (e.g. Detox, Maestro, Appium/WebdriverIO). */
  e2e: string[];
}

/** A workspace-level mobile finding: a mobile target plus the project it belongs to. */
export interface MobileFinding extends MobileTarget {
  /** Project name where the mobile app was detected. */
  project: string;
}

export interface ProjectRef {
  name: string;
  /** Path relative to the workspace root; `.` for the root project. */
  path: string;
  language?: string;
  framework?: string;
  /** Auth libraries detected in this project's manifest. */
  auth?: ProjectAuth[];
  /** React Native / Expo target, when this project is a mobile app. */
  mobile?: MobileTarget;
}

export interface Workspace {
  root: string;
  description: string;
  languages: string[];
  framework?: string;
  conventions: string[];
  /** Auth stack detected across projects — the base the QA phase relies on. */
  auth?: AuthFinding[];
  /** React Native / Expo apps detected — what mobile QA runs against. */
  mobile?: MobileFinding[];
  projects: ProjectRef[];
  /** Coding-rule files found across repos (Cursor, Claude, Trae, …). */
  ruleSources: RuleSource[];
  /** Top-level directory names (without trailing slash), sorted. */
  folderMap: string[];
}

/**
 * Render a `Workspace` to the markdown that gets written to
 * `.chamba/workspace.md`. Deterministic on purpose — no timestamps — so that
 * `workspace_reload` produces meaningful diffs instead of churn.
 */
export function renderWorkspaceMarkdown(ws: Workspace): string {
  const lines: string[] = [];

  lines.push('# Workspace');
  lines.push('');
  lines.push('> Generated by chamba. Editable by hand — chamba will not overwrite');
  lines.push('> your edits; `workspace_reload` only proposes a diff.');
  lines.push('');
  lines.push('## Description');
  lines.push('');
  lines.push(
    ws.description.trim().length > 0 ? ws.description.trim() : '_No description detected._',
  );
  lines.push('');

  lines.push('## Languages');
  lines.push('');
  if (ws.languages.length > 0) {
    for (const lang of ws.languages) lines.push(`- ${lang}`);
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Framework');
  lines.push('');
  lines.push(ws.framework ?? '_None detected._');
  lines.push('');

  lines.push('## Conventions');
  lines.push('');
  if (ws.conventions.length > 0) {
    for (const c of ws.conventions) lines.push(`- ${c}`);
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Auth');
  lines.push('');
  lines.push('> How this app authenticates and provisions users — the base the QA co-pilot');
  lines.push('> and planner rely on. Detected from dependencies; enrich by hand: the roles');
  lines.push('> model, how test users are created, and which provider owns identity.');
  lines.push('');
  if (ws.auth && ws.auth.length > 0) {
    for (const a of ws.auth) {
      const pkgs = a.packages.map((p) => `\`${p}\``).join(', ');
      const where = a.projects.length > 0 ? ` (${a.projects.join(', ')})` : '';
      lines.push(`- **${a.provider}** — ${pkgs}${where}`);
    }
  } else {
    lines.push('_No auth library detected from dependencies._');
    lines.push('');
    lines.push(
      'If this app has auth, document it here by hand: the provider, how users + roles ' +
        'are provisioned, and how to create test users. The QA phase needs this — the qa ' +
        'agent never creates identity-provider users, it asks you to.',
    );
  }
  lines.push('');

  if (ws.mobile && ws.mobile.length > 0) {
    lines.push('## Mobile');
    lines.push('');
    lines.push('> React Native / Expo apps detected — what the QA co-pilot runs acceptance');
    lines.push('> tests against on a simulator/emulator. chamba only detects and lists; your');
    lines.push("> editor's mobile MCP (Expo, device control) or the terminal drives the device.");
    lines.push('> The login step stays human, as everywhere else in QA.');
    lines.push('');
    for (const m of ws.mobile) lines.push(`- ${renderMobileFinding(m)}`);
    lines.push('');
  }

  lines.push('## Coding rules');
  lines.push('');
  lines.push('> Rule files found per repo (read non-exclusively across editors). chamba');
  lines.push('> loads their content into context at task time.');
  lines.push('');
  if (ws.ruleSources.length > 0) {
    for (const r of ws.ruleSources) {
      lines.push(`- \`${r.path}\` — ${r.editor} (${r.repo})`);
    }
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Active projects');
  lines.push('');
  if (ws.projects.length > 0) {
    for (const p of ws.projects) {
      const meta = [p.language, p.framework].filter(Boolean).join(', ');
      lines.push(`- **${p.name}** (\`${p.path}\`)${meta ? ` — ${meta}` : ''}`);
    }
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Folder map');
  lines.push('');
  if (ws.folderMap.length > 0) {
    for (const dir of ws.folderMap) lines.push(`- ${dir}/`);
  } else {
    lines.push('_Empty._');
  }
  lines.push('');

  return lines.join('\n');
}

/** One `## Mobile` bullet, e.g. `**app** — Expo (managed), iOS·Android, EAS, e2e: Detox`. */
function renderMobileFinding(m: MobileFinding): string {
  const parts: string[] = [];
  if (m.expo) parts.push(`Expo (${m.expo})`);
  else if (m.reactNative) parts.push('React Native');
  if (m.platforms.length > 0) {
    parts.push(m.platforms.map((p) => (p === 'ios' ? 'iOS' : 'Android')).join('·'));
  }
  if (m.hasDevClient) parts.push('dev-client');
  if (m.hasEas) parts.push('EAS');
  if (m.e2e.length > 0) parts.push(`e2e: ${m.e2e.join(', ')}`);
  const suffix = parts.length > 0 ? ` — ${parts.join(', ')}` : '';
  return `**${m.project}**${suffix}`;
}
