import type { RuleSource } from './rules.js';

/** Relative path (from workspace root) of the chamba workspace file. */
export const WORKSPACE_DIR = '.chamba';
export const WORKSPACE_FILE = 'workspace.md';
export const WORKSPACE_RELATIVE_PATH = `${WORKSPACE_DIR}/${WORKSPACE_FILE}`;

/** An auth library/provider detected in one project, with the packages that signalled it. */
export interface ProjectAuth {
  provider: string;
  packages: string[];
}

/** A workspace-level auth finding: a provider, the packages, and where it's used. */
export interface AuthFinding {
  /** Provider/library, e.g. "Auth0", "Firebase Auth", "AWS Cognito". */
  provider: string;
  /** Dependency names that signalled it. */
  packages: string[];
  /** Project names where it was detected. */
  projects: string[];
}

export interface ProjectRef {
  name: string;
  /** Path relative to the workspace root; `.` for the root project. */
  path: string;
  language?: string;
  framework?: string;
  /** Auth libraries detected in this project's manifest. */
  auth?: ProjectAuth[];
}

export interface Workspace {
  root: string;
  description: string;
  languages: string[];
  framework?: string;
  conventions: string[];
  /** Auth stack detected across projects — the base the QA phase relies on. */
  auth?: AuthFinding[];
  projects: ProjectRef[];
  /** Coding-rule files found across repos (Cursor, Claude, Trae, …). */
  ruleSources: RuleSource[];
  /** Top-level directory names (without trailing slash), sorted. */
  folderMap: string[];
}

/**
 * Render a `Workspace` to the markdown that gets written to
 * `.chamba/workspace.md`. Deterministic on purpose — no timestamps — so that
 * `workspace_reload` produces meaningful diffs instead of churn.
 */
export function renderWorkspaceMarkdown(ws: Workspace): string {
  const lines: string[] = [];

  lines.push('# Workspace');
  lines.push('');
  lines.push('> Generated by chamba. Editable by hand — chamba will not overwrite');
  lines.push('> your edits; `workspace_reload` only proposes a diff.');
  lines.push('');
  lines.push('## Description');
  lines.push('');
  lines.push(
    ws.description.trim().length > 0 ? ws.description.trim() : '_No description detected._',
  );
  lines.push('');

  lines.push('## Languages');
  lines.push('');
  if (ws.languages.length > 0) {
    for (const lang of ws.languages) lines.push(`- ${lang}`);
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Framework');
  lines.push('');
  lines.push(ws.framework ?? '_None detected._');
  lines.push('');

  lines.push('## Conventions');
  lines.push('');
  if (ws.conventions.length > 0) {
    for (const c of ws.conventions) lines.push(`- ${c}`);
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Auth');
  lines.push('');
  lines.push('> How this app authenticates and provisions users — the base the QA co-pilot');
  lines.push('> and planner rely on. Detected from dependencies; enrich by hand: the roles');
  lines.push('> model, how test users are created, and which provider owns identity.');
  lines.push('');
  if (ws.auth && ws.auth.length > 0) {
    for (const a of ws.auth) {
      const pkgs = a.packages.map((p) => `\`${p}\``).join(', ');
      const where = a.projects.length > 0 ? ` (${a.projects.join(', ')})` : '';
      lines.push(`- **${a.provider}** — ${pkgs}${where}`);
    }
  } else {
    lines.push('_No auth library detected from dependencies._');
    lines.push('');
    lines.push(
      'If this app has auth, document it here by hand: the provider, how users + roles ' +
        'are provisioned, and how to create test users. The QA phase needs this — the qa ' +
        'agent never creates identity-provider users, it asks you to.',
    );
  }
  lines.push('');

  lines.push('## Coding rules');
  lines.push('');
  lines.push('> Rule files found per repo (read non-exclusively across editors). chamba');
  lines.push('> loads their content into context at task time.');
  lines.push('');
  if (ws.ruleSources.length > 0) {
    for (const r of ws.ruleSources) {
      lines.push(`- \`${r.path}\` — ${r.editor} (${r.repo})`);
    }
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Active projects');
  lines.push('');
  if (ws.projects.length > 0) {
    for (const p of ws.projects) {
      const meta = [p.language, p.framework].filter(Boolean).join(', ');
      lines.push(`- **${p.name}** (\`${p.path}\`)${meta ? ` — ${meta}` : ''}`);
    }
  } else {
    lines.push('_None detected._');
  }
  lines.push('');

  lines.push('## Folder map');
  lines.push('');
  if (ws.folderMap.length > 0) {
    for (const dir of ws.folderMap) lines.push(`- ${dir}/`);
  } else {
    lines.push('_Empty._');
  }
  lines.push('');

  return lines.join('\n');
}
